---
version: "3"

networks:
  inside:
     external: true
  outside:
     external: true
services:
  dockersocket:
     container_name: dockersocket
     image: tecnativa/docker-socket-proxy
     ports:
      - host:2375:2375
     volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     networks:
      - inside
      - outside
     environment:
       CONTAINERS: 1
       POST: 0
     privileged: true
     restart: unless-stopped
