version: '3.5'

networks:
  inside:
    driver: bridge
    external: true
    
services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - your-host-ip:8000:8000
    volumes:
      - ./media/youtube:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=your-host-ip         # set your host name
      - TA_USERNAME=user_name           # your initial TA credentials
      - TA_PASSWORD=your-strong-password             # your initial TA credentials
      - ELASTIC_PASSWORD=your-elastic-strong-password        # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - inside
#-------
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./archivist-redis:/data
    depends_on:
      - archivist-es
    networks:
      - inside
#------
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.11.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=your-elastic-strong-password"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./archivist-es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    networks:
      - inside
