---
services:
  cloudflaretunnel:
    container_name: cloudflaretunnel
    image: cloudflare/cloudflared:2023.10.0
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=your cloudflare tunnel token
    command: tunnel --no-autoupdate run
    networks:
      - outside



      
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      # -- Internal Network - all dockers
      - Your-ip:80:80   # http
      - Your-ip:443:443 # https
      # -- External Network = connection to firewall
      - Your-ip:81:81
      - Your-ip:444:444
      #----TCP Network----#
#      - Your-ip:22001:22000   # WIP
      # -- Enable Dashboard, don't do in production
      - Your-ip:8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro  # Static config: main config
      - ./config/rules/:/etc/traefik/rules/ # Routers, Services, Middlewares, Certificates(Stores options)
      - ./config/certs/:/etc/traefik/certs/ # Certs directory 
    environment:
      DOCKER_HOST: dockersocket # External docker socket as docker
      CF_API_EMAIL: mail@mail.com
      CF_DNS_API_TOKEN: YOUR-CF_DNS_API_TOKEN
    networks:
      - inside
      - outside
    restart: unless-stopped



networks:
# cloudflare to traefik
  outside:
    driver: bridge
    external: true
# traefik to dockersocket
  inside:
    driver: bridge
    external: true
