global:
  checkNewVersion: false
  sendAnonymousUsage: false
# -----------------------------------------------------------------------------------                
log:
  level: DEBUG  # in Production use ERROR
  format: common
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: common
  filePath: /var/log/traefik/access.log
  bufferingSize: "50"
# ------------------------------------------------------------------------------------               
api:
  dashboard: true
  insecure: true
  disableDashboardAd: true
  debug: false

serversTransport:
  insecureSkipVerify: true
# ------------------------------------------------------------------------------------              
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      middlewares:
        # - authentik-bouncer@file
        # - crowdsec-bouncer@file
        - securityHeaders@file
      tls:
        certResolver: cloudflare
        domains:
          - main: domain.com
            sans:
              - '*.doamin.com'

certificatesResolver:
  cloudflre:
    acme:
      email: email@gmail.com
      storage: /etc/traefik/certs/acme.json
      # caServer: 'https://acme-v02.api.letsencrypt.org/directory' # Production
      caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory' # Testing
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        # Used to make sure the dns challenge is propagated to the rights dns servers
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

providers:
  providersThrottleDuration: 2s
  file:
    directory: /etc/traefik/conf/
    watch: true
#    
  docker:
    watch: true
    exposedByDefault: false
    # VERRY IMPORTANT
    endpoint: "tcp://dockersocket:2375" # Uncomment if you are using docker socket proxy
#   
