version: "3"

networks:
  inside:
    external: true
    
services:
  guacamole:
    image: jwetzell/guacamole
    container_name: guacamole
    volumes:
      - ./postgres:/config
    ports:
      - your-host-ip:8080:8080
    networks:
      - inside
