version: '3'

networks:
  inside:
    driver: bridge
    external: true

services:
  uvdesk-db:
    image: mysql:5.7
    container_name: uvdesk-db
    volumes:
      - ./uvdeskdb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: uvdesk # database user
      MYSQL_DATABASE: uvdesk # databse name
      MYSQL_PASSWORD: your-strong-password
      MYSQL_ROOT_PASSWORD: your-strong-password
    networks:
      - inside

  uvdesk:
    image: nuttcorp/uvdesk:latest
    container_name: uvdesk
    depends_on:
      - uvdesk-db
    tty: true
    environment:
        MYSQL_USER: uvdesk #database user name from "db" service
        MYSQL_DATABASE: uvdesk #database user name from "db" service
        MYSQL_PASSWORD: your-strong-password
        MYSQL_ROOT_PASSWORD: your-strong-password
    ports:
      - your-host-ip:6744:80
    networks:
      - inside
