networks:
# cloudflare to traefik
  outside:
    driver: bridge
    external: true
# traefik to dockersocket
  inside:
    driver: bridge
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      # -- Internal Network - all dockers
      - Your-ip:80:80   # http
      - Your-ip:443:443 # https
      # -- External Network = connection to firewall
      - Your-ip:81:81
      - Your-ip:444:444
      #----TCP Network----#
#      - Your-ip:22001:22000   # WIP
      # -- Enable Dashboard, don't do in production
      - Your-ip:8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/http/:/etc/traefik/http/     # http routers, services, middlewares
#      - ./config/tcp/:/etc/traefik/tcp/     `# tcp routers, services, middlewares
#      - ./config/udp/:/etc/traefik/udp/      # udp routers, services, middlewares
      - ./config/certs/:/etc/traefik/certs/
    environment:
      DOCKER_HOST: dockersocket
      CF_API_EMAIL: mail@mail.com
      CF_DNS_API_TOKEN: YOUR-CF_DNS_API_TOKEN
    networks:
      - inside
      - outside
    restart: unless-stopped
