version: '3'                                                                                                          
networks:  
  outside:     # cloudflare to traefik                                                                                                        
    driver: bridge                                                                                                    
    external: true 
  inside:      # traefik to dockersocket ==> reads all dockers apps on this network                                                                                                        
    driver: bridge                                                                                                    
    external: true                                                                                                    

services:                                                                                                             
  dockersocket:                                                                                                       
    image: tecnativa/docker-socket-proxy                                                                              
    container_name: dockersocket                                                                                      
    volumes:                                                                                                          
      - /var/run/docker.sock:/var/run/docker.sock                                                                     
    networks:                                                                                                         
      - inside                                                                                                        
    environment:                                                                                                      
      CONTAINERS: 1                                                                                                   
      POST: 0                                                                                                         
    privileged: true                                                                                                  
    restart: unless-stopped                                                                                           

  traefik:                                                                                                            
    image: traefik:latest                                                                                             
    container_name: traefik                                                                                           
    ports:                                                                                                            
      # -- Internal Network                                                                                           
      - 80:80   # http                                                                                                
      - 443:443 # https
      # -- External Network from firewall
      # -- Enable Dashboard, don't do in production                                                                   
      - 8080:8080                                                                                                     
    volumes:                                                                                                          
      - /etc/localtime:/etc/localtime:ro                                                                                                                                           
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro                                                            
      - ./config/midwares/:/etc/traefik/midwares/                                                                     
      - ./config/certs/:/etc/traefik/certs/                                                                                                                                                                                              
# -- (Optional) When using Cloudflare as Cert Resolver                                                                
    environment:                                                                                                      
      DOCKER_HOST: dockersocket                                                                                       
#      - CF_API_EMAIL=mail@gmail.com                                                                       
#      - CF_DNS_API_TOKEN=API_TOKEN                        
    networks:                                                                                                         
      - inside
      - outside
    depends_on:                                                                                                       
      - dockersocket                                                                                                  
    restart: unless-stopped                                                                                           
