version: "3.1"

networks:
  inside:
    external: true

services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: your-strong-password
      POSTGRES_DB: peppermint
    networks:
      - inside

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - your-host-ip:3000:3000
      - your-host-ip:5003:5003
    restart: always
    depends_on:
      - peppermint_postgres
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider $$API_URL"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "your-strong-password" #same as in peppermint_postgres service
      DB_HOST: "peppermint_postgres" #database service name ex. "peppermint_postgres"
      SECRET: 'peppermint4life'
    networks:
      - inside
